# Generated by Django 5.0.6 on 2024-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_event_description_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.CharField(default='no', max_length=255, null=True),
        ),
    ]
