# Generated by Django 5.0.6 on 2024-09-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_event_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('suggestion', models.TextField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
